packages:
  - "packages/*"
allowBuilds:
  esbuild: false
minimumReleaseAge: 10080
overrides:
  '@vecrea/au3te-ts-common': link:../../../../home/node/.local/share/pnpm/global/5/node_modules/@vecrea/au3te-ts-common
  '@vecrea/au3te-ts-server': link:../../../../home/node/.local/share/pnpm/global/5/node_modules/@vecrea/au3te-ts-server
  '@vecrea/user-management-apis': link:../../../../home/node/.local/share/pnpm/global/5/node_modules/@vecrea/user-management-apis
trustPolicy: no-downgrade
